
language: node_js
node_js:
  - "7"
install:
  - "cd js && npm run prep"
script:
  - "cd js"
  - "npm run deploy"
  - "mkdir build"
  - "cp -r dist build/dist"
  - "cp -r decoder-model build/decoder-model"
  - "cp -r encoder-model build/encoder-model"
  - "cp index.html build/index.html"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: "js/build"
